// User data
export const mockUsers = [
  {
    id: "user1",
    name: "Alex Johnson",
    username: "alexj",
    email: "alex@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Developer",
    skills: ["JavaScript", "React", "Node.js"],
    bio: "Full-stack developer with 3 years of experience",
    level: 24,
    points: 2450,
    badges: ["Problem Solver", "Team Player", "Quick Learner"],
    projects: ["project1", "project3"],
    availability: "Weekends",
    interests: ["Web Development", "Mobile Apps", "AI"],
    languages: ["English", "Spanish"],
    location: "San Francisco, CA",
    github: "github.com/alexj",
    linkedin: "linkedin.com/in/alexj",
    website: "alexj.dev",
    joinedDate: "2022-03-15",
  },
  {
    id: "user2",
    name: "Priya Sharma",
    username: "priyas",
    email: "priya@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Designer",
    skills: ["UI/UX", "Figma", "Adobe XD"],
    bio: "UI/UX designer passionate about creating intuitive interfaces",
    level: 18,
    points: 1820,
    badges: ["Design Guru", "Creative Thinker", "Accessibility Advocate"],
    projects: ["project2"],
    availability: "Evenings",
    interests: ["Design Systems", "Accessibility", "Animation"],
    languages: ["English", "Hindi"],
    location: "New York, NY",
    github: "github.com/priyas",
    linkedin: "linkedin.com/in/priyas",
    website: "priyasharma.design",
    joinedDate: "2022-05-22",
  },
  {
    id: "user3",
    name: "Miguel Rodriguez",
    username: "miguelr",
    email: "miguel@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Data Scientist",
    skills: ["Python", "Machine Learning", "Data Analysis"],
    bio: "Data scientist with a background in statistical analysis",
    level: 15,
    points: 1540,
    badges: ["Data Wizard", "Algorithm Master", "Analytical Mind"],
    projects: ["project4"],
    availability: "Full-time",
    interests: ["Machine Learning", "Data Visualization", "Big Data"],
    languages: ["English", "Spanish", "Portuguese"],
    location: "Austin, TX",
    github: "github.com/miguelr",
    linkedin: "linkedin.com/in/miguelr",
    website: "miguelr.io",
    joinedDate: "2022-07-10",
  },
  {
    id: "user4",
    name: "Sarah Kim",
    username: "sarahk",
    email: "sarah@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Product Manager",
    skills: ["Product Strategy", "Agile", "User Research"],
    bio: "Product manager focused on user-centered design and agile methodologies",
    level: 22,
    points: 2230,
    badges: ["Product Visionary", "Agile Expert", "User Advocate"],
    projects: ["project1", "project5"],
    availability: "Part-time",
    interests: ["Product Management", "User Research", "Market Analysis"],
    languages: ["English", "Korean"],
    location: "Seattle, WA",
    github: "github.com/sarahk",
    linkedin: "linkedin.com/in/sarahk",
    website: "sarahkim.pm",
    joinedDate: "2022-02-18",
  },
  {
    id: "user5",
    name: "David Chen",
    username: "davidc",
    email: "david@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Backend Developer",
    skills: ["Java", "Spring Boot", "Microservices"],
    bio: "Backend developer specializing in scalable microservices architecture",
    level: 20,
    points: 2050,
    badges: ["Code Architect", "Performance Optimizer", "Security Specialist"],
    projects: ["project3", "project6"],
    availability: "Weekdays",
    interests: ["System Design", "Cloud Computing", "DevOps"],
    languages: ["English", "Mandarin"],
    location: "Boston, MA",
    github: "github.com/davidc",
    linkedin: "linkedin.com/in/davidc",
    website: "davidchen.dev",
    joinedDate: "2022-04-05",
  },
]

// Project data
export const mockProjects = [
  {
    id: "project1",
    title: "EcoTrack",
    description: "A mobile app that helps users track and reduce their carbon footprint",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Mobile", "React Native", "Sustainability"],
    members: ["user1", "user4"],
    progress: 75,
    status: "In Progress",
    deadline: "2023-12-15",
    createdAt: "2023-08-10",
    updatedAt: "2023-11-05",
    repository: "github.com/ecotrack/app",
    website: "ecotrack.app",
    likes: 42,
    views: 320,
  },
  {
    id: "project2",
    title: "MindfulMe",
    description: "A meditation and mindfulness platform with guided sessions and progress tracking",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Web", "React", "Mental Health"],
    members: ["user2"],
    progress: 90,
    status: "Almost Complete",
    deadline: "2023-11-30",
    createdAt: "2023-07-22",
    updatedAt: "2023-11-10",
    repository: "github.com/mindfulme/web",
    website: "mindfulme.co",
    likes: 38,
    views: 275,
  },
  {
    id: "project3",
    title: "CodeCollab",
    description: "A real-time collaborative code editor with integrated version control",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Web", "JavaScript", "Collaboration"],
    members: ["user1", "user5"],
    progress: 60,
    status: "In Progress",
    deadline: "2024-01-20",
    createdAt: "2023-09-05",
    updatedAt: "2023-11-12",
    repository: "github.com/codecollab/editor",
    website: "codecollab.io",
    likes: 56,
    views: 410,
  },
  {
    id: "project4",
    title: "DataVizPro",
    description: "A data visualization library with customizable charts and graphs",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Data", "Python", "Visualization"],
    members: ["user3"],
    progress: 40,
    status: "Early Development",
    deadline: "2024-02-28",
    createdAt: "2023-10-15",
    updatedAt: "2023-11-08",
    repository: "github.com/datavizpro/lib",
    website: "datavizpro.dev",
    likes: 29,
    views: 215,
  },
  {
    id: "project5",
    title: "HealthHub",
    description: "A healthcare management system for patients and providers",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["Web", "Healthcare", "Full Stack"],
    members: ["user4"],
    progress: 80,
    status: "Testing",
    deadline: "2023-12-10",
    createdAt: "2023-08-30",
    updatedAt: "2023-11-15",
    repository: "github.com/healthhub/platform",
    website: "healthhub.care",
    likes: 45,
    views: 330,
  },
  {
    id: "project6",
    title: "SmartHome",
    description: "An IoT platform for connecting and managing smart home devices",
    image: "/placeholder.svg?height=200&width=300",
    tags: ["IoT", "Java", "Hardware"],
    members: ["user5"],
    progress: 65,
    status: "In Progress",
    deadline: "2024-01-15",
    createdAt: "2023-09-20",
    updatedAt: "2023-11-10",
    repository: "github.com/smarthome/hub",
    website: "smarthome.tech",
    likes: 37,
    views: 290,
  },
]

// Hackathon data
export const mockHackathons = [
  {
    id: "hackathon1",
    title: "Climate Tech Hackathon",
    description: "Build innovative solutions to address climate change challenges",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2023-12-10",
    endDate: "2023-12-12",
    location: "San Francisco, CA",
    format: "In-person",
    prizes: ["$10,000 Grand Prize", "$5,000 Runner-up", "$2,500 People's Choice"],
    sponsors: ["GreenTech", "ClimateVentures", "SustainableFuture"],
    registrationDeadline: "2023-12-01",
    maxTeamSize: 5,
    currentRegistrations: 42,
    website: "climatehack.org",
    tags: ["Climate", "Sustainability", "GreenTech"],
    difficulty: "Intermediate",
  },
  {
    id: "hackathon2",
    title: "AI for Good Hackathon",
    description: "Develop AI solutions that address social and humanitarian challenges",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2024-01-15",
    endDate: "2024-01-17",
    location: "Virtual",
    format: "Online",
    prizes: ["$8,000 First Place", "$4,000 Second Place", "$2,000 Third Place"],
    sponsors: ["AI Foundation", "TechForGood", "GlobalImpact"],
    registrationDeadline: "2024-01-05",
    maxTeamSize: 4,
    currentRegistrations: 78,
    website: "aiforgood.dev",
    tags: ["AI", "Machine Learning", "Social Impact"],
    difficulty: "Advanced",
  },
  {
    id: "hackathon3",
    title: "HealthTech Innovation Challenge",
    description: "Create digital solutions to improve healthcare access and outcomes",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2023-11-25",
    endDate: "2023-11-26",
    location: "Boston, MA",
    format: "Hybrid",
    prizes: ["$7,500 Winner", "$3,500 Runner-up", "Mentorship Opportunities"],
    sponsors: ["MedTech Alliance", "HealthInnovate", "CareVentures"],
    registrationDeadline: "2023-11-20",
    maxTeamSize: 3,
    currentRegistrations: 35,
    website: "healthtechhack.com",
    tags: ["Healthcare", "MedTech", "Digital Health"],
    difficulty: "Intermediate",
  },
  {
    id: "hackathon4",
    title: "Blockchain Revolution Hackathon",
    description: "Build decentralized applications that solve real-world problems",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    location: "Virtual",
    format: "Online",
    prizes: ["$12,000 First Prize", "$6,000 Second Prize", "$3,000 Third Prize"],
    sponsors: ["BlockChain Ventures", "DecentralFuture", "CryptoInnovate"],
    registrationDeadline: "2024-01-25",
    maxTeamSize: 4,
    currentRegistrations: 62,
    website: "blockchainhack.io",
    tags: ["Blockchain", "Web3", "Cryptocurrency"],
    difficulty: "Advanced",
  },
  {
    id: "hackathon5",
    title: "EdTech for All Hackathon",
    description: "Create educational technology solutions that make learning accessible to everyone",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2023-12-18",
    endDate: "2023-12-19",
    location: "Chicago, IL",
    format: "In-person",
    prizes: ["$5,000 Winner", "$2,500 Runner-up", "Incubator Access"],
    sponsors: ["EduFuture", "LearnTech", "AccessibleEd"],
    registrationDeadline: "2023-12-10",
    maxTeamSize: 3,
    currentRegistrations: 28,
    website: "edtechhack.org",
    tags: ["Education", "Accessibility", "Learning"],
    difficulty: "Beginner",
  },
  {
    id: "hackathon6",
    title: "Smart Cities Hackathon",
    description: "Develop IoT and data-driven solutions for urban challenges",
    image: "/placeholder.svg?height=200&width=300",
    startDate: "2024-01-20",
    endDate: "2024-01-22",
    location: "Singapore",
    format: "In-person",
    prizes: ["$15,000 Grand Prize", "$7,500 Innovation Award", "$5,000 Sustainability Award"],
    sponsors: ["UrbanTech", "SmartLiving", "CityInnovate"],
    registrationDeadline: "2024-01-10",
    maxTeamSize: 5,
    currentRegistrations: 45,
    website: "smartcitieshack.com",
    tags: ["Smart Cities", "IoT", "Urban Planning"],
    difficulty: "Intermediate",
  },
]

// Mentor data
export const mockMentors = [
  {
    id: "mentor1",
    name: "Dr. Emily Chen",
    role: "Senior Software Architect",
    company: "TechGiant Inc.",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Dr. Chen has over 15 years of experience in software architecture and systems design. She specializes in scalable cloud solutions and distributed systems.",
    expertise: ["Cloud Architecture", "Distributed Systems", "System Design", "Microservices"],
    languages: ["English", "Mandarin"],
    availability: "Weekends",
    rating: 4.9,
    reviews: 45,
    sessions: 120,
    website: "emilychen.tech",
    linkedin: "linkedin.com/in/emilychen",
    github: "github.com/emilychen",
    twitter: "twitter.com/emilychen",
  },
  {
    id: "mentor2",
    name: "Marcus Johnson",
    role: "Lead UX Designer",
    company: "DesignHub",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Marcus is a UX design leader with a passion for creating intuitive and accessible user experiences. He has worked with startups and Fortune 500 companies.",
    expertise: ["UX Design", "UI Design", "Design Systems", "User Research", "Accessibility"],
    languages: ["English", "French"],
    availability: "Evenings",
    rating: 4.8,
    reviews: 38,
    sessions: 95,
    website: "marcusjohnson.design",
    linkedin: "linkedin.com/in/marcusjohnson",
    github: "github.com/marcusjohnson",
    twitter: "twitter.com/marcusjohnson",
  },
  {
    id: "mentor3",
    name: "Sophia Rodriguez",
    role: "AI Research Scientist",
    company: "AI Innovations Lab",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Sophia is an AI researcher specializing in machine learning and natural language processing. She has published numerous papers and contributed to open-source AI projects.",
    expertise: ["Machine Learning", "Natural Language Processing", "Deep Learning", "AI Ethics"],
    languages: ["English", "Spanish"],
    availability: "Flexible",
    rating: 4.9,
    reviews: 42,
    sessions: 110,
    website: "sophiarodriguez.ai",
    linkedin: "linkedin.com/in/sophiarodriguez",
    github: "github.com/sophiarodriguez",
    twitter: "twitter.com/sophiarodriguez",
  },
  {
    id: "mentor4",
    name: "James Wilson",
    role: "Senior Product Manager",
    company: "ProductForge",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "James is a product leader with experience in building and scaling products from concept to market. He specializes in agile methodologies and product strategy.",
    expertise: ["Product Management", "Agile", "Product Strategy", "Go-to-Market", "User Stories"],
    languages: ["English"],
    availability: "Weekdays",
    rating: 4.7,
    reviews: 35,
    sessions: 85,
    website: "jameswilson.pm",
    linkedin: "linkedin.com/in/jameswilson",
    github: "github.com/jameswilson",
    twitter: "twitter.com/jameswilson",
  },
  {
    id: "mentor5",
    name: "Aisha Patel",
    role: "DevOps Engineer",
    company: "CloudScale Solutions",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Aisha is a DevOps expert with a focus on CI/CD pipelines, infrastructure as code, and cloud-native technologies. She helps teams implement efficient development workflows.",
    expertise: ["DevOps", "CI/CD", "Docker", "Kubernetes", "AWS", "Infrastructure as Code"],
    languages: ["English", "Hindi", "Gujarati"],
    availability: "Weekends",
    rating: 4.8,
    reviews: 40,
    sessions: 100,
    website: "aishapatel.dev",
    linkedin: "linkedin.com/in/aishapatel",
    github: "github.com/aishapatel",
    twitter: "twitter.com/aishapatel",
  },
  {
    id: "mentor6",
    name: "David Kim",
    role: "Blockchain Developer",
    company: "BlockTech Innovations",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "David is a blockchain developer and consultant who has worked on multiple DeFi and NFT projects. He specializes in smart contracts and decentralized applications.",
    expertise: ["Blockchain", "Smart Contracts", "Ethereum", "Solidity", "Web3", "DeFi"],
    languages: ["English", "Korean"],
    availability: "Evenings",
    rating: 4.9,
    reviews: 36,
    sessions: 90,
    website: "davidkim.blockchain",
    linkedin: "linkedin.com/in/davidkim",
    github: "github.com/davidkim",
    twitter: "twitter.com/davidkim",
  },
]

// Chatbot data
export const mockChatbotMessages = [
  {
    id: "msg1",
    role: "system",
    content: "Hello! I'm CollabBot, your AI assistant for Collab-Sphere X. How can I help you today?",
    timestamp: "2023-11-15T10:00:00Z",
  },
  {
    id: "msg2",
    role: "user",
    content: "I'm looking for a project to join. Can you help me find one?",
    timestamp: "2023-11-15T10:01:30Z",
  },
  {
    id: "msg3",
    role: "system",
    content:
      "Of course! I can help you find a project that matches your interests and skills. Could you tell me what technologies or areas you're interested in?",
    timestamp: "2023-11-15T10:01:45Z",
  },
  {
    id: "msg4",
    role: "user",
    content: "I'm interested in React and machine learning projects.",
    timestamp: "2023-11-15T10:02:30Z",
  },
  {
    id: "msg5",
    role: "system",
    content:
      "Great! Based on your interests in React and machine learning, I'd recommend checking out the 'DataVizPro' project, which combines data visualization with ML components. You might also be interested in 'MindfulMe', which uses React for its frontend. Would you like more details about either of these projects?",
    timestamp: "2023-11-15T10:02:50Z",
  },
  {
    id: "msg6",
    role: "user",
    content: "Tell me more about DataVizPro.",
    timestamp: "2023-11-15T10:03:30Z",
  },
  {
    id: "msg7",
    role: "system",
    content:
      "DataVizPro is a data visualization library with customizable charts and graphs. It's currently in early development (40% complete) and uses Python for backend processing with a React frontend for rendering visualizations. The project incorporates machine learning for predictive analytics features. The team is looking for contributors with experience in data visualization, React, or machine learning algorithms. Would you like me to connect you with the project lead?",
    timestamp: "2023-11-15T10:03:50Z",
  },
  {
    id: "msg8",
    role: "user",
    content: "Yes, that would be great!",
    timestamp: "2023-11-15T10:04:30Z",
  },
  {
    id: "msg9",
    role: "system",
    content:
      "I've sent a connection request to Miguel Rodriguez, the project lead for DataVizPro. You should receive a notification when they respond. In the meantime, you can view more details about the project on the project page. Is there anything else you'd like help with?",
    timestamp: "2023-11-15T10:04:50Z",
  },
  {
    id: "msg10",
    role: "user",
    content: "How can I improve my profile to attract more project collaborations?",
    timestamp: "2023-11-15T10:05:30Z",
  },
  {
    id: "msg11",
    role: "system",
    content:
      "Great question! Here are some tips to enhance your profile: 1) Add detailed descriptions of your skills and experience levels, 2) Upload examples of your past work or link to your portfolio, 3) Complete your availability schedule so teams know when you can collaborate, 4) Earn skill badges by completing challenges in our learning tracks, and 5) Participate in community discussions to increase your visibility. Would you like me to guide you through updating any specific part of your profile?",
    timestamp: "2023-11-15T10:05:50Z",
  },
]

// Learning tracks data
export const mockLearningTracks = [
  {
    id: "track1",
    title: "Full-Stack Web Development",
    description: "Learn to build complete web applications from frontend to backend",
    image: "/placeholder.svg?height=200&width=300",
    level: "Intermediate",
    duration: "12 weeks",
    modules: [
      {
        id: "module1",
        title: "Frontend Fundamentals",
        description: "HTML, CSS, and JavaScript basics",
        duration: "2 weeks",
        completed: true,
      },
      {
        id: "module2",
        title: "React Essentials",
        description: "Building interactive UIs with React",
        duration: "3 weeks",
        completed: true,
      },
      {
        id: "module3",
        title: "Backend Development",
        description: "Server-side programming with Node.js",
        duration: "3 weeks",
        completed: false,
      },
      {
        id: "module4",
        title: "Database Integration",
        description: "Working with SQL and NoSQL databases",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module5",
        title: "Full-Stack Project",
        description: "Building and deploying a complete application",
        duration: "2 weeks",
        completed: false,
      },
    ],
    progress: 40,
    enrolledUsers: 245,
    rating: 4.8,
    reviews: 68,
    tags: ["Web Development", "JavaScript", "React", "Node.js"],
  },
  {
    id: "track2",
    title: "Machine Learning Fundamentals",
    description: "Master the basics of machine learning and data science",
    image: "/placeholder.svg?height=200&width=300",
    level: "Advanced",
    duration: "10 weeks",
    modules: [
      {
        id: "module1",
        title: "Introduction to Data Science",
        description: "Data analysis and visualization basics",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module2",
        title: "Supervised Learning",
        description: "Classification and regression algorithms",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module3",
        title: "Unsupervised Learning",
        description: "Clustering and dimensionality reduction",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module4",
        title: "Neural Networks",
        description: "Building and training neural networks",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module5",
        title: "ML Project",
        description: "Implementing a complete machine learning solution",
        duration: "2 weeks",
        completed: false,
      },
    ],
    progress: 0,
    enrolledUsers: 180,
    rating: 4.9,
    reviews: 45,
    tags: ["Machine Learning", "Python", "Data Science", "AI"],
  },
  {
    id: "track3",
    title: "Mobile App Development",
    description: "Create cross-platform mobile applications",
    image: "/placeholder.svg?height=200&width=300",
    level: "Intermediate",
    duration: "8 weeks",
    modules: [
      {
        id: "module1",
        title: "Mobile Development Basics",
        description: "Introduction to mobile app architecture",
        duration: "1 week",
        completed: false,
      },
      {
        id: "module2",
        title: "React Native Fundamentals",
        description: "Building UIs with React Native",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module3",
        title: "State Management",
        description: "Managing application state effectively",
        duration: "2 weeks",
        completed: false,
      },
      {
        id: "module4",
        title: "Native Device Features",
        description: "Accessing device capabilities",
        duration: "1 week",
        completed: false,
      },
      {
        id: "module5",
        title: "Mobile App Project",
        description: "Building and publishing a mobile application",
        duration: "2 weeks",
        completed: false,
      },
    ],
    progress: 0,
    enrolledUsers: 150,
    rating: 4.7,
    reviews: 38,
    tags: ["Mobile Development", "React Native", "iOS", "Android"],
  },
]
